dist: xenial
language: rust
rust:
- stable
- beta
- nightly
node_js: 10

cache:
- cargo

jobs:
  include:
  - stage: "Wasm Build"
    rust: stable
    before_script:
    - cargo install wasm-pack
    script:
    - wasm-pack build
    - wasm-pack test
  - stage: "Rust Build"
    rust:
    - stable
    - beta
    - nightly
    script:
    - cargo build
    - cargo test
  allowed_failures:
  - rust: nightly
  fast_finish: true
