[package]
name = "scp-username-module"
version = "0.1.0"
authors = ["not_a_seagull <notaseagull048@gmail.com>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
askama = "0.8"
wasm-bindgen = "0.2.55"

[profile.release]
lto = true
